question1:
	echo "Question 1"
	echo "Modified Dining Philosophers Problem"
	gcc -o question1 question1.c
	./question1

question2:
	echo "Question 2"
	echo "Interprocess Communication"

	gcc -o p1 p1.c
	gcc -o p2 p2.c


question3:
	echo "Question 3"
	echo "Kernel Module a.k.a KernelHacking"

	gcc -o question3.c


clean:
	rm -f question1 question2 p1 p2 question3